### ISSUE TITLE
actions/stale へ移行する?

### ISSUE THREAD

**Issue by znz** [oss-gate/issue-cleaner#15]
GitHub Actions に https://github.com/actions/stale があって、別サイトで bot を動かさなくても GitHub だけで完結できるようなので、機能的に問題なさそうなら actions/stale に移行するのはどうでしょうか?

**Comment by knokmki612** [comment]
共有ありがとうございます、probotをやめてGitHub Actionsに移行するのはアリな気がしています。

現状のissue-cleanerは2日後にクローズするようになってますが、クローズの条件をアンケートの提出がされたら閉じるように変更することを考えてます。 #11 
こちらについてもprobotではなくactionsでやれそうなので、検討したいです。

**Comment by knokmki612** [comment]
文意が分かりにくくなってしまいました。クローズする条件の変更を考えていて、staleだとその条件に対しては機能が合わないので、actionsに移行するのであれば新しいactionを作りたいと思っています、という意味です

**Comment by knokmki612** [comment]
#21 で、新しいactionsを作る方向で進めていこうかと思います。
